### ISSUE TITLE
Use filebeat to dump Eve.json to kafka

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#143]
Currently, logstash reads the eve.json from the file system. To support a distributed sensor deployment, filebeat should perform this function in the sensor. Logstash will continue to read from Kafka to elasticsearch

**Comment by akniffe1** [comment]
Good call, this should probably be done with FSF rockout.log as well so that all sensor collection (as currently defined) is remote ready. You can configure filebeats to publish a prospector's output to a specific kafka topic based on the "type" field, which can be appended to each prospector event by adding:

```
document_type: <kafka_topic_name>
```

and then the publish decision can be made in outputs.kafka with

```
output.kafka:
  hosts: ["localhost:9092"]
  topic: '%{[type]}'
....
```

A note on doing this with FSF:
When I last checked, you'll want to tell filebeats to decode specific json fields--otherwise it won't traverse nested keys past a certain point (I think its 1 or two levels of nesting). That should look like this: 

```
processors:
 - decode_json_fields:
     when:
       contains:
         type: <kafka_fsf_topic_name>
     fields: ["Scan Time", "Filename", "objects", "Source", "meta", "Alert" ,"Summary"]
     process_array: true
     max_depth: 10
```
