### ISSUE TITLE
Filebeat.yml Missing Modules Section

### ISSUE THREAD

**Issue by peasead** [rocknsm/rock#366]
`rocknsm-buildstamp`
```
[Main]
Product=RockNSM
Version=2.3-1902
BugURL=https://github.com/rocknsm/rock/issues/
IsFinal=True
UUID=201711080000.x86_64
Build=20190222-0830
[Compose]
Lorax=19.6.78-1
```
The contents of `/etc/filebeat/filebeat.yml` has
```
#=========================== Filebeat prospectors =============================

filebeat.config.inputs:
  enabled: true
  path: configs/*.yml

processors:
 - decode_json_fields:
     fields: ["message","Scan Time", "Filename", "objects", "Source", "meta", "Alert" ,"Summary"]
     process_array: true
...
```
but it should also contain the following so you can load Elastic Filebeat modules.
```
...
filebeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml
...
```
Currently if you try to use the `modules` command of the `filebeat` program, you're presented with an error
```
sudo filebeat modules list
Error in modules manager: modules management requires 'filebeat.config.modules.path' setting
```
